name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 32 # Ensure we can generate changelogs

      - name: "Zip release files" # Only if the version has been updated
        run: |
          echo "Creating a release zip file..."
          zip -r scriptio-release.zip icons/ modules/ main.js manifest.json package.json preload.js renderer.js settings.html
          echo "Done!"

      - name: "Create Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            scriptio-release.zip
